spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bella?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

logging:
 level:
   com.bella.start.dao: trace

mybatis-plus:
  mapper-locations:
    - com/bella/start/mapper/*.xml